---
title: "Sampling the Data"
author: "Jakraya (Park) Chatsiriwech - Group 4"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data set

```{r}
data <- read.csv(file = "uber_lyft_cleaned_v5.csv", header = TRUE, stringsAsFactors = TRUE)
```


# Sampling 5000 observations

```{r}
set.seed(92)
index <- sample(1:nrow(data), size = 5000, replace = TRUE)   # since a lot of data, sampling with replacement is approximately the same as without replacement
length(unique(index))   # it has 4988 unique values with replacement

sub_data <- data[index,]
```


# Visualisation of sub_data

```{r}
str(sub_data)
summary(sub_data)   

# Calculate the proportion in sub_data vs real data
## By weekday
cbind("Data" = sum(data$Weekday == "Weekday") / nrow(data),  #73.79%
      "Subdata" = sum(sub_data$Weekday == "Weekday") / nrow(sub_data))  #72.88%

## By Peak
cbind("Data" = sum(data$Peak == "Peak") / nrow(data),   #27.42%
      "Subdata" = sum(sub_data$Peak == "Peak") / nrow(sub_data))  #26.6%

## By cab_type
cbind("Data" = sum(data$cab_type == "Uber") / nrow(data),   #51.82%
      "Subdata" = sum(sub_data$cab_type == "Uber") / nrow(sub_data))  #52.66%

## By Cab_Name
cbind("Data" = sum(data$Cab_Name == "Regular") / nrow(data),   #41.9696%
      "Subdata" = sum(sub_data$Cab_Name == "Regular") / nrow(sub_data))  #41.9%
cbind("Data" = sum(data$Cab_Name == "Luxury") / nrow(data),   #41.36%
      "Subdata" = sum(sub_data$Cab_Name == "Luxury") / nrow(sub_data))  #42.02%

## By Weather
cbind("Data" = sum(data$Weather == "Clear") / nrow(data),   #12.58%
      "Subdata" = sum(sub_data$Weather == "Clear") / nrow(sub_data))  #12.1%
cbind("Data" = sum(data$Weather == "Cloudy") / nrow(data),   #75.04%
      "Subdata" = sum(sub_data$Weather == "Cloudy") / nrow(sub_data))  #75.6%

# Visualise the distribution of continuous variables
par(mfrow = c(1,2))
hist(data$price, freq = FALSE)
hist(sub_data$price, freq = FALSE)   # histogram of price has same shape

par(mfrow = c(1,2))
hist(data$distance, freq = FALSE)
hist(sub_data$distance, freq = FALSE)  # histogram of distance has roughly the same shape

par(mfrow = c(1,2))
hist(data$temperature, freq = FALSE)
hist(sub_data$temperature, freq = FALSE)  # histogram of temp has roughly the same shape

par(mfrow = c(1,2))
hist(data$precipIntensity, freq = FALSE, breaks = 20)
hist(sub_data$precipIntensity, freq = FALSE, breaks = 20)  # histogram of precipIntensity has roughly the same shape

par(mfrow = c(1,2))
hist(data$humidity, freq = FALSE, breaks = 20)
hist(sub_data$humidity, freq = FALSE, breaks = 20) # histogram of humidity has roughly the same shape

par(mfrow = c(1,2))
hist(data$windSpeed, freq = FALSE, breaks = 20)
hist(sub_data$windSpeed, freq = FALSE, breaks = 20)  # histogram of windSpeed has roughly the same shape

par(mfrow = c(1,2))
hist(data$visibility, freq = FALSE, breaks = 20)
hist(sub_data$visibility, freq = FALSE, breaks = 20)  # histogram of visibility has roughly the same shape

# Surge_multiplier
par(mfrow = c(1,2))
hist(data$surge_multiplier, freq = FALSE, breaks = 20)
hist(sub_data$surge_multiplier, freq = FALSE, breaks = 20)
summary(data$surge_multiplier)
summary(sub_data$surge_multiplier)

cbind("Data" = sum(data$surge_multiplier == 1) / nrow(data),   #96.71%
      "Subdata" = sum(sub_data$surge_multiplier == 1) / nrow(sub_data))  #96.08%
cbind("Data" = sum(data$surge_multiplier == 1.25) / nrow(data),   #1.74%
      "Subdata" = sum(sub_data$surge_multiplier == 1.25) / nrow(sub_data))  #2.06%
cbind("Data" = sum(data$surge_multiplier == 1.5) / nrow(data),   #0.79%
      "Subdata" = sum(sub_data$surge_multiplier == 1.5) / nrow(sub_data))  #0.98%
cbind("Data" = sum(data$surge_multiplier == 1.75) / nrow(data),   #0.38%
      "Subdata" = sum(sub_data$surge_multiplier == 1.75) / nrow(sub_data))  #0.4%
cbind("Data" = sum(data$surge_multiplier == 2) / nrow(data),   #0.35%
      "Subdata" = sum(sub_data$surge_multiplier == 2) / nrow(sub_data))  #0.46%
cbind("Data" = sum(data$surge_multiplier == 2.5) / nrow(data),   #0.024%
      "Subdata" = sum(sub_data$surge_multiplier == 2.5) / nrow(sub_data))  #0.02%
cbind("Data" = sum(data$surge_multiplier == 3) / nrow(data),   #0.0019%
      "Subdata" = sum(sub_data$surge_multiplier == 3) / nrow(sub_data))  #0.0%
```

# Standardize the price with surge_multiplier and take log

```{r}
sub_data[,14] <- sub_data$price / sub_data$surge_multiplier
sub_data[,15] <- log(sub_data[,14])
names(sub_data)[14:15] <- c("std_price", "log_std_price")

# Move std_price and log_std_price in front
sub_data <- sub_data[, c(1, 14:15, 2:13)]

# Export this to a csv file
write.csv(sub_data, file = "Sampled_Data.csv", row.names = FALSE, col.names = TRUE)
```

```{r}
test <- read.csv(file = "Sampled_Data.csv", header = TRUE, stringsAsFactors = TRUE)
```

